// Bitcoin1070 PRO v10.1 - かな／銘柄名／シンボル 横断検索マスタ
window.B1070_ASSET_MASTER = [
  {type:'crypto',symbol:'BTC',name:'Bitcoin',coinGeckoId:'bitcoin',keywords:['ビットコイン']},
  {type:'crypto',symbol:'ETH',name:'Ethereum',coinGeckoId:'ethereum',keywords:['イーサリアム']},
  {type:'crypto',symbol:'XRP',name:'XRP',coinGeckoId:'ripple',keywords:['リップル']},
  {type:'crypto',symbol:'SOL',name:'Solana',coinGeckoId:'solana',keywords:['ソラナ']},
  {type:'crypto',symbol:'SUI',name:'Sui',coinGeckoId:'sui',keywords:['スイ']},
  {type:'crypto',symbol:'RENDER',name:'Render',coinGeckoId:'render-token',keywords:['レンダー','RNDR']},
  {type:'crypto',symbol:'TAO',name:'Bittensor',coinGeckoId:'bittensor',keywords:['ビテンソル']},
  {type:'crypto',symbol:'SHIB',name:'Shiba Inu',coinGeckoId:'shiba-inu',keywords:['シバイヌ']},

  {type:'jp',symbol:'285A',name:'キオクシアホールディングス',reading:'きおくしあほーるでぃんぐす',yahooSymbol:'285A.T',keywords:['キオクシア','KIOXIA','キオクシアHD']},
  {type:'jp',symbol:'3556',name:'リネットジャパングループ',reading:'りねっとじゃぱんぐるーぷ',yahooSymbol:'3556.T',keywords:['リネットジャパン','リネット']},
  {type:'jp',symbol:'1605',name:'INPEX',reading:'いんぺっくす',yahooSymbol:'1605.T',keywords:['インペックス']},
  {type:'jp',symbol:'7011',name:'三菱重工業',reading:'みつびしじゅうこうぎょう',yahooSymbol:'7011.T',keywords:['三菱重工']},
  {type:'jp',symbol:'7012',name:'川崎重工業',reading:'かわさきじゅうこうぎょう',yahooSymbol:'7012.T',keywords:['川崎重工']},
  {type:'jp',symbol:'7013',name:'IHI',reading:'あいえいちあい',yahooSymbol:'7013.T',keywords:['アイエイチアイ']},
  {type:'jp',symbol:'5803',name:'フジクラ',reading:'ふじくら',yahooSymbol:'5803.T',keywords:[]},
  {type:'jp',symbol:'6857',name:'アドバンテスト',reading:'あどばんてすと',yahooSymbol:'6857.T',keywords:[]},
  {type:'jp',symbol:'3778',name:'さくらインターネット',reading:'さくらいんたーねっと',yahooSymbol:'3778.T',keywords:['さくら']},
  {type:'jp',symbol:'5631',name:'日本製鋼所',reading:'にほんせいこうしょ',yahooSymbol:'5631.T',keywords:[]},
  {type:'jp',symbol:'5401',name:'日本製鉄',reading:'にっぽんせいてつ',yahooSymbol:'5401.T',keywords:[]},
  {type:'jp',symbol:'6594',name:'ニデック',reading:'にでっく',yahooSymbol:'6594.T',keywords:['日本電産']},
  {type:'jp',symbol:'6981',name:'村田製作所',reading:'むらたせいさくしょ',yahooSymbol:'6981.T',keywords:['村田']},
  {type:'jp',symbol:'8035',name:'東京エレクトロン',reading:'とうきょうえれくとろん',yahooSymbol:'8035.T',keywords:['東エレク']},
  {type:'jp',symbol:'135A',name:'VRAIN Solution',reading:'ぶれいんそりゅーしょん',yahooSymbol:'135A.T',keywords:['VRAIN','ブレインソリューション']},
  {type:'jp',symbol:'3350',name:'メタプラネット',reading:'めたぷらねっと',yahooSymbol:'3350.T',keywords:[]},
  {type:'jp',symbol:'6501',name:'日立製作所',reading:'ひたちせいさくしょ',yahooSymbol:'6501.T',keywords:['日立']},
  {type:'jp',symbol:'6702',name:'富士通',reading:'ふじつう',yahooSymbol:'6702.T',keywords:[]},
  {type:'jp',symbol:'6758',name:'ソニーグループ',reading:'そにーぐるーぷ',yahooSymbol:'6758.T',keywords:['ソニー']},
  {type:'jp',symbol:'7203',name:'トヨタ自動車',reading:'とよたじどうしゃ',yahooSymbol:'7203.T',keywords:['トヨタ']},
  {type:'jp',symbol:'8306',name:'三菱UFJフィナンシャル・グループ',reading:'みつびしゆーえふじぇいふぃなんしゃるぐるーぷ',yahooSymbol:'8306.T',keywords:['三菱UFJ','MUFG']},
  {type:'jp',symbol:'8316',name:'三井住友フィナンシャルグループ',reading:'みついすみともふぃなんしゃるぐるーぷ',yahooSymbol:'8316.T',keywords:['三井住友','SMFG']},

  {type:'jp',symbol:'9984',name:'ソフトバンクグループ',reading:'そふとばんくぐるーぷ',yahooSymbol:'9984.T',keywords:['ソフトバンクグループ','SBG']},
  {type:'jp',symbol:'9434',name:'ソフトバンク',reading:'そふとばんく',yahooSymbol:'9434.T',keywords:['ソフトバンク株式会社']},
  {type:'jp',symbol:'6269',name:'三井海洋開発',reading:'みついかいようかいはつ',yahooSymbol:'6269.T',keywords:['MODEC','MODEC INC JAPAN']},
  {type:'jp',symbol:'7201',name:'日産自動車',reading:'にっさんじどうしゃ',yahooSymbol:'7201.T',keywords:['日産']},
  {type:'jp',symbol:'7267',name:'本田技研工業',reading:'ほんだぎけんこうぎょう',yahooSymbol:'7267.T',keywords:['ホンダ','HONDA']},
  {type:'jp',symbol:'9983',name:'ファーストリテイリング',reading:'ふぁーすとりていりんぐ',yahooSymbol:'9983.T',keywords:['ユニクロ']},
  {type:'jp',symbol:'7974',name:'任天堂',reading:'にんてんどう',yahooSymbol:'7974.T',keywords:[]},
  {type:'jp',symbol:'4063',name:'信越化学工業',reading:'しんえつかがくこうぎょう',yahooSymbol:'4063.T',keywords:['信越化学']},
  {type:'jp',symbol:'8411',name:'みずほフィナンシャルグループ',reading:'みずほふぃなんしゃるぐるーぷ',yahooSymbol:'8411.T',keywords:['みずほ']},
  {type:'jp',symbol:'8591',name:'オリックス',reading:'おりっくす',yahooSymbol:'8591.T',keywords:[]},

  {type:'us',symbol:'NVDA',name:'NVIDIA',yahooSymbol:'NVDA',keywords:['エヌビディア']},
  {type:'us',symbol:'AAPL',name:'Apple',yahooSymbol:'AAPL',keywords:['アップル']},
  {type:'us',symbol:'MSFT',name:'Microsoft',yahooSymbol:'MSFT',keywords:['マイクロソフト']},
  {type:'us',symbol:'TSLA',name:'Tesla',yahooSymbol:'TSLA',keywords:['テスラ']},
  {type:'us',symbol:'AMZN',name:'Amazon',yahooSymbol:'AMZN',keywords:['アマゾン']},
  {type:'us',symbol:'GOOGL',name:'Alphabet',yahooSymbol:'GOOGL',keywords:['グーグル','Google']},
  {type:'us',symbol:'META',name:'Meta Platforms',yahooSymbol:'META',keywords:['メタ']},
  {type:'us',symbol:'AMD',name:'Advanced Micro Devices',yahooSymbol:'AMD',keywords:['エーエムディー']},
  {type:'us',symbol:'AVGO',name:'Broadcom',yahooSymbol:'AVGO',keywords:['ブロードコム']}
];
