// Bitcoin1070 PRO v16.1.1 - Daily Decision Center core
(() => {
  'use strict';
  const KEYS={plans:'bitcoin1070_trade_plans_v14',alerts:'bitcoin1070_alert_rules_v14'};
  const read=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch(_){return fallback}};
  const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch(_){return false}};
  const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};
  const keyOf=a=>`${a?.type||'unknown'}:${String(a?.symbol||'').trim().toUpperCase()}`;
  function storedAssets(){try{if(typeof loadAssetsFromStorage==='function')return loadAssetsFromStorage([]);const raw=localStorage.getItem('bitcoin1070_v3_assets');const parsed=JSON.parse(raw||'[]');return Array.isArray(parsed)?parsed:[]}catch(_){return[]}}
  function holdings(){const runtime=(typeof assets!=='undefined'&&Array.isArray(assets))?assets:null;return (runtime||storedAssets()).filter(a=>['crypto','jp','us'].includes(a?.type))}
  function livePrice(asset){try{if(asset.type==='crypto'){const id=String(asset.coinGeckoId||'').trim().toLowerCase();const sym=String(asset.symbol||'').trim().toUpperCase();const row=(typeof latestCryptoPrices!=='undefined'&&latestCryptoPrices)?(latestCryptoPrices[id]??latestCryptoPrices[sym]):null;const direct=num(row?.jpy??row?.price??row);if(direct!==null)return direct}if(asset.type==='jp'||asset.type==='us'){const symbol=String(asset.symbol||'').trim().toUpperCase();if(typeof stockPrices!=='undefined'&&stockPrices){const p=num(stockPrices[symbol]);if(p!==null)return p}if(typeof latestStockPrices!=='undefined'&&latestStockPrices){const p=num(latestStockPrices[symbol]);if(p!==null)return p}}}catch(_){}return null}
  const priceOf=a=>num(a?.currentPrice??a?.price??a?.jpyPrice??a?.marketPrice)??livePrice(a);
  const qtyOf=a=>num(a?.amount??a?.quantity??a?.qty??a?.shares)??0;
  function valueOf(a){const explicit=num(a?.currentValue??a?.marketValue??a?.valueJpy);if(explicit!==null)return explicit;if(typeof getAssetValue==='function'){try{const v=num(getAssetValue(a));if(v!==null)return Math.max(0,v)}catch(_){}}const p=priceOf(a),q=qtyOf(a);if(p===null)return 0;let value=p*q;if(a.type==='us'&&typeof getUsdJpyRate==='function'){try{const fx=num(getUsdJpyRate());if(fx!==null)value*=fx}catch(_){}}return Math.max(0,value)}
  function cashValue(){try{return typeof loadCashBalance==='function'?(num(loadCashBalance())??0):(num(localStorage.getItem('bitcoin1070_v12_1_cash_jpy'))??0)}catch(_){return 0}}
  function signalFor(asset,daily){const change=num(daily?.percent),label=asset.type==='crypto'?'24時間比':'前日比';if(change===null)return{level:'neutral',label:'中立',score:50,reasons:[`${label}データ待ち`]};const reasons=[`${label} ${change>=0?'+':''}${change.toFixed(2)}%`];if(change>=3)return{level:'bull',label:'強気',score:72,reasons};if(change<=-3)return{level:'bear',label:'弱気',score:28,reasons};return{level:'neutral',label:'中立',score:50+Math.round(change*4),reasons}}
  function health(){const values=holdings().map(a=>({asset:a,value:valueOf(a)})).filter(x=>x.value>0);const cash=cashValue();const invested=values.reduce((s,x)=>s+x.value,0),total=invested+cash;if(!total)return{score:null,label:'データ待ち',issues:['価格更新後も診断できない場合は再読み込みしてください']};const byType={cash};values.forEach(x=>{byType[x.asset.type]=(byType[x.asset.type]||0)+x.value});const topAsset=values.length?Math.max(...values.map(x=>x.value/total)):0,topClass=Math.max(...Object.values(byType).map(v=>v/total));const cashRatio=cash/total;let risk=0;const issues=[];if(topAsset>.45){risk+=28;issues.push('単一銘柄への集中度が高め')}else if(topAsset>.30){risk+=15;issues.push('最大銘柄の比率を確認')}if(topClass>.70){risk+=25;issues.push('資産クラスの偏りが大きい')}else if(topClass>.55){risk+=12;issues.push('資産クラスがやや集中')}if(cashRatio<.03){risk+=15;issues.push('待機資金が少なめ')}const score=Math.max(0,Math.min(100,100-risk));return{score,label:score>=80?'良好':score>=60?'標準':score>=40?'要確認':'高リスク',issues:issues.length?issues:['大きな集中リスクは検出されていません'],total,cashRatio,topAsset,topClass}}
  function strategies(signals,h){const out=[],bears=signals.filter(x=>x.signal.level==='bear'),bulls=signals.filter(x=>x.signal.level==='bull');if(h.score!==null&&h.score<60)out.push({icon:'🛡️',title:'リスク配分を確認',text:h.issues[0]});if(bears.length)out.push({icon:'⚠️',title:`弱気シグナル ${bears.length}銘柄`,text:`${bears.slice(0,3).map(x=>x.asset.symbol).join('・')} の値動きを確認`});if(bulls.length)out.push({icon:'📈',title:`強気シグナル ${bulls.length}銘柄`,text:'追い買いを急がず、設定した利確ラインとの距離を確認'});if(!out.length)out.push({icon:'⏸️',title:'今日は様子見',text:'大きな偏りや強いシグナルは未検出。無理に売買しない選択も有効です'});return out.slice(0,3)}
  function plans(){return read(KEYS.plans,{})}function savePlan(assetKey,plan){const all=plans();all[assetKey]={...plan,updatedAt:new Date().toISOString()};return write(KEYS.plans,all)}function alerts(){return read(KEYS.alerts,[])}function saveAlerts(rules){return write(KEYS.alerts,Array.isArray(rules)?rules:[])}function evaluateAlerts(prices={}){return alerts().filter(r=>{const p=num(prices[r.assetKey]),t=num(r.target);if(p===null||t===null||!r.enabled)return false;return r.operator==='>='?p>=t:p<=t})}
  function dailyValues(){for(const key of ['bitcoin1070_daily_changes_v14_0','bitcoin1070_daily_changes_v13_1']){try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d?.values)return d.values}catch(_){}}return{}}
  function snapshot(){const daily=dailyValues(),signals=holdings().map(asset=>({asset,signal:signalFor(asset,daily[keyOf(asset)])})),h=health();return{signals,health:h,strategies:strategies(signals,h)}}
  window.Bitcoin1070DecisionCenter={KEYS,keyOf,holdings,priceOf,valueOf,cashValue,signalFor,health,strategies,plans,savePlan,alerts,saveAlerts,evaluateAlerts,snapshot,version:'16.1.1'};
})();
