// Bitcoin1070 PRO v16.2 - AI Commander UI
(()=>{
'use strict';
const yen=v=>Number.isFinite(Number(v))?'¥'+Math.round(Number(v)).toLocaleString('ja-JP'):'--';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function radarHTML(){const scan=window.Bitcoin1070OpportunityRadar?.scan?.();if(!scan)return '';const opportunities=(scan.opportunities||[]).slice(0,3),hot=(scan.overheated||[]).slice(0,2);return `<div class="ios-radar"><div class="ios-radar-head"><strong>📡 暴落チャンスレーダー</strong><small>保有銘柄を横断監視</small></div>${opportunities.length?`<div class="ios-radar-list">${opportunities.map(r=>`<div class="ios-radar-row"><span><b>${esc(r.asset.symbol)}</b> ${esc(r.state.label)}</span><strong>${r.score}/100</strong><small>${r.change===null?'変動率待ち':esc(r.changeLabel)+' '+(r.change>=0?'+':'')+r.change.toFixed(2)+'%'}・品質 ${r.quality}/100</small>${r.reasons.length?`<em>${r.reasons.map(esc).join(' / ')}</em>`:''}</div>`).join('')}</div>`:'<p class="ios-radar-empty">現在、強い押し目候補はありません。</p>'}${hot.length?`<div class="ios-hot"><strong>⚠️ 追い買い注意</strong>${hot.map(r=>`<span>${esc(r.asset.symbol)}・過熱 ${r.heat}/100</span>`).join('')}</div>`:''}<small class="ios-disclaimer">${esc(scan.note)}</small></div>`}
function riskAdvice(r){if(!r)return[];const a=r.allocation||{},out=[];if((a.cash??0)<5)out.push({title:'待機資金',text:'現金比率が5%未満。新規資金を現金として残すと急落時の選択肢が増えます。'});if(r.largest?.weight>=35)out.push({title:`${r.largest.symbol}集中`,text:`最大銘柄が${r.largest.weight}%。30%以下を目安にすると単一銘柄ショックへの依存を抑えられます。`});if((a.crypto??0)>=30)out.push({title:'暗号資産比率',text:`暗号資産${a.crypto}%。値動きが大きいため、市場急落シナリオへの寄与が高めです。`});if(!out.length)out.push({title:'配分',text:'大きな単一要因は検出されていません。現在の分散を維持しながら定期確認してください。'});return out.slice(0,3)}
function estimateImproved(r){if(!r?.rows?.length)return null;const rows=r.rows.map(x=>({...x,asset:{...x.asset}}));let cash=rows.find(x=>x.type==='cash');const total=Number(r.totalJpy)||rows.reduce((s,x)=>s+Number(x.value||0),0);if(!total)return null;const targetCash=total*.10;if(!cash){cash={asset:{type:'cash',symbol:'JPY'},type:'cash',value:0,stress:{normal:0,severe:0}};rows.push(cash)}const largest=rows.filter(x=>x.type!=='cash').sort((a,b)=>b.value-a.value)[0];let shift=Math.max(0,targetCash-cash.value);if(largest)shift=Math.min(shift,Math.max(0,largest.value-total*.30));if(shift<=0)return null;largest.value-=shift;cash.value+=shift;const severe=rows.reduce((s,x)=>s+(x.value/total)*Number(x.stress?.severe||0),0);const hhi=rows.filter(x=>x.type!=='cash').reduce((s,x)=>s+Math.pow(x.value/total,2),0);const crypto=rows.filter(x=>x.type==='crypto').reduce((s,x)=>s+x.value/total,0);const score=Math.max(0,Math.min(100,Math.round(100-severe*115-hhi*18-crypto*12)));return{score,shift:Math.round(shift),cashPct:Math.round(cash.value/total*1000)/10,largestPct:Math.round(largest.value/total*1000)/10}}
function riskHTML(r){if(!r)return '';const sc=(r.scenarios||[]).map(s=>`<div class="ios-stress-row"><span>${esc(s.name)}</span><strong>-${Number(s.lossPct||0).toFixed(1)}%</strong></div>`).join('');const a=r.allocation||{},advice=riskAdvice(r),improved=estimateImproved(r);return `<div class="ios-risk"><span>🛡️ ポートフォリオ耐久度</span><strong>${r.score}/100・${esc(r.label)}</strong><div class="ios-stress-list">${sc}</div><small>構成：暗号 ${a.crypto??0}% / 米国株 ${a.us??0}% / 日本株 ${a.jp??0}% / 現金 ${a.cash??0}%${r.largest?`・最大 ${esc(r.largest.symbol)} ${r.largest.weight}%`:''}</small><details><summary>なぜこの点数？・改善案</summary><div class="ios-reasons">${advice.map(x=>`<span><b>${esc(x.title)}</b> ${esc(x.text)}</span>`).join('')}</div>${improved?`<p><b>参考シミュレーション：</b> 最大銘柄から約${yen(improved.shift)}を待機資金へ移し、現金${improved.cashPct}%・最大銘柄${improved.largestPct}%にした場合、簡易再計算では耐久度は約 <b>${improved.score}/100</b>。売却推奨ではなく配分比較です。</p>`:''}</details><small>${esc(r.method||'ストレスシナリオによる参考評価')}</small></div>`}
function evidenceHTML(r){const e=r.evidence;if(!e)return'';return `<div class="ios-checks">${(e.checks||[]).map(x=>`<span>${x.ok?'✓':'△'} ${esc(x.name)}</span>`).join('')}</div><p><b>テクニカル確認:</b> ${e.positive}/${e.available}一致${e.strongReady?'・強気判定条件を満たす':e.weakReady?'・弱気判定条件を満たす':'・確定判定は保留'}</p>`}
function render(){const root=document.getElementById('investmentOSCommander'),api=window.Bitcoin1070InvestmentOS;if(!root||!api)return;const c=api.commander();if(!c){root.innerHTML='<div class="loading-state">AI司令塔の判断材料を取得中...</div>';return;}const actions=c.actions||[];root.innerHTML=`<div class="ios-head"><div><span class="eyebrow">INVESTMENT OS</span><h2>🧠 AI司令塔</h2></div><div class="ios-quality"><small>データ品質</small><strong>${c.dataQuality}/100</strong></div></div><p class="ios-lead">今日優先して確認する判断を最大3件に絞ります。</p><div class="ios-actions">${actions.map((r,i)=>`<article class="ios-action"><div class="ios-rank">${i+1}</div><div class="ios-action-main"><div class="ios-action-title"><strong>${esc(r.asset.symbol)}</strong><span>${esc(r.action)}</span></div>${r.provisional?`<div class="ios-status-note">⚠️ ${esc(r.statusDetail)}。下のスコアは取得済みデータだけで計算した暫定値です。</div>`:`<div class="ios-status-note ios-status-ok">✓ ${esc(r.statusDetail)}</div>`}<div class="ios-scores"><span>総合 <b>${r.factor.score}/100</b></span><span>買い場 <b>${r.opportunity.score}/100</b></span><span>信頼度 <b>${r.confidence}/100</b></span></div>${r.plan?.available?`<div class="ios-levels"><span>買い候補 ${yen(r.plan.buyZone)}</span><span>利確候補 ${yen(r.plan.takeProfit1)}</span><span>損切り候補 ${yen(r.plan.stopLoss)}</span></div>`:`<div class="ios-status-note">売買候補価格：テクニカル取得後に表示</div>`}<details><summary>判断根拠・データ品質</summary><div class="ios-reasons">${(r.factor.factors||[]).slice(0,6).map(f=>`<span>${esc(f.name)} ${Math.round(f.score)}/100</span>`).join('')}</div>${evidenceHTML(r)}<div class="ios-checks">${r.quality.checks.map(x=>`<span>${x.status==='live'?'✓':x.status==='stale'?'△':'×'} ${esc(x.name)}</span>`).join('')}</div>${r.missing?.length?`<p><b>不足データ:</b> ${r.missing.map(esc).join(' / ')}</p>`:''}${r.stale?.length?`<p><b>更新待ち:</b> ${r.stale.map(esc).join(' / ')}</p>`:''}${r.plan?.invalidation?.length?`<p><b>判断を撤回する条件:</b> ${r.plan.invalidation.map(esc).join(' / ')}</p>`:''}</details></div></article>`).join('')}</div>${radarHTML()}${riskHTML(c.risk)}<small class="ios-disclaimer">${esc(c.disclaimer)}</small>`}
['bitcoin1070:investment-os-ready','bitcoin1070:opportunity-radar-ready','bitcoin1070:data-layer-updated','bitcoin1070:daily-changes-updated','bitcoin1070:professional-ai-updated','bitcoin1070:technical-autoload-complete','b1070:market-updated'].forEach(e=>window.addEventListener(e,()=>setTimeout(render,30)));document.addEventListener('DOMContentLoaded',()=>{render();setTimeout(render,1200);setTimeout(render,3500)});window.Bitcoin1070InvestmentOSUI={render,version:'16.2'};
})();
