// Bitcoin1070 PRO v16.1 - AI Commander UI
(()=>{
'use strict';
const yen=v=>Number.isFinite(Number(v))?'¥'+Math.round(Number(v)).toLocaleString('ja-JP'):'--';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function radarHTML(){const scan=window.Bitcoin1070OpportunityRadar?.scan?.();if(!scan)return '';const opportunities=(scan.opportunities||[]).slice(0,3),hot=(scan.overheated||[]).slice(0,2);return `<div class="ios-radar"><div class="ios-radar-head"><strong>📡 暴落チャンスレーダー</strong><small>保有銘柄を横断監視</small></div>${opportunities.length?`<div class="ios-radar-list">${opportunities.map(r=>`<div class="ios-radar-row"><span><b>${esc(r.asset.symbol)}</b> ${esc(r.state.label)}</span><strong>${r.score}/100</strong><small>${r.change===null?'変動率待ち':esc(r.changeLabel)+' '+(r.change>=0?'+':'')+r.change.toFixed(2)+'%'}・品質 ${r.quality}/100</small>${r.reasons.length?`<em>${r.reasons.map(esc).join(' / ')}</em>`:''}</div>`).join('')}</div>`:'<p class="ios-radar-empty">現在、強い押し目候補はありません。</p>'}${hot.length?`<div class="ios-hot"><strong>⚠️ 追い買い注意</strong>${hot.map(r=>`<span>${esc(r.asset.symbol)}・過熱 ${r.heat}/100</span>`).join('')}</div>`:''}<small class="ios-disclaimer">${esc(scan.note)}</small></div>`}
function riskHTML(r){if(!r)return '';const sc=(r.scenarios||[]).map(s=>`<div class="ios-stress-row"><span>${esc(s.name)}</span><strong>-${Number(s.lossPct||0).toFixed(1)}%</strong></div>`).join('');const a=r.allocation||{};return `<div class="ios-risk"><span>🛡️ ポートフォリオ耐久度</span><strong>${r.score}/100・${esc(r.label)}</strong><div class="ios-stress-list">${sc}</div><small>構成：暗号 ${a.crypto??0}% / 米国株 ${a.us??0}% / 日本株 ${a.jp??0}% / 現金 ${a.cash??0}%${r.largest?`・最大 ${esc(r.largest.symbol)} ${r.largest.weight}%`:''}</small><small>${esc(r.method||'ストレスシナリオによる参考評価')}</small></div>`}
function render(){const root=document.getElementById('investmentOSCommander'),api=window.Bitcoin1070InvestmentOS;if(!root||!api)return;const c=api.commander();if(!c){root.innerHTML='<div class="loading-state">AI司令塔の判断材料を取得中...</div>';return;}const actions=c.actions||[];root.innerHTML=`<div class="ios-head"><div><span class="eyebrow">INVESTMENT OS</span><h2>🧠 AI司令塔</h2></div><div class="ios-quality"><small>データ品質</small><strong>${c.dataQuality}/100</strong></div></div><p class="ios-lead">今日優先して確認する判断を最大3件に絞ります。</p><div class="ios-actions">${actions.map((r,i)=>`<article class="ios-action"><div class="ios-rank">${i+1}</div><div class="ios-action-main"><div class="ios-action-title"><strong>${esc(r.asset.symbol)}</strong><span>${esc(r.action)}</span></div>${r.provisional?`<div class="ios-status-note">⚠️ ${esc(r.statusDetail)}。下のスコアは取得済みデータだけで計算した暫定値です。</div>`:`<div class="ios-status-note ios-status-ok">✓ ${esc(r.statusDetail)}</div>`}<div class="ios-scores"><span>総合 <b>${r.factor.score}/100</b></span><span>買い場 <b>${r.opportunity.score}/100</b></span><span>信頼度 <b>${r.confidence}/100</b></span></div>${r.plan?.available?`<div class="ios-levels"><span>買い候補 ${yen(r.plan.buyZone)}</span><span>利確候補 ${yen(r.plan.takeProfit1)}</span><span>損切り候補 ${yen(r.plan.stopLoss)}</span></div>`:`<div class="ios-status-note">売買候補価格：テクニカル取得後に表示</div>`}<details><summary>判断根拠・データ品質</summary><div class="ios-reasons">${(r.factor.factors||[]).slice(0,6).map(f=>`<span>${esc(f.name)} ${Math.round(f.score)}/100</span>`).join('')}</div><div class="ios-checks">${r.quality.checks.map(x=>`<span>${x.status==='live'?'✓':x.status==='stale'?'△':'×'} ${esc(x.name)}</span>`).join('')}</div>${r.missing?.length?`<p><b>不足データ:</b> ${r.missing.map(esc).join(' / ')}</p>`:''}${r.stale?.length?`<p><b>更新待ち:</b> ${r.stale.map(esc).join(' / ')}</p>`:''}${r.plan?.invalidation?.length?`<p><b>判断を撤回する条件:</b> ${r.plan.invalidation.map(esc).join(' / ')}</p>`:''}</details></div></article>`).join('')}</div>${radarHTML()}${riskHTML(c.risk)}<small class="ios-disclaimer">${esc(c.disclaimer)}</small>`}
['bitcoin1070:investment-os-ready','bitcoin1070:opportunity-radar-ready','bitcoin1070:data-layer-updated','bitcoin1070:daily-changes-updated','bitcoin1070:professional-ai-updated','bitcoin1070:technical-autoload-complete','b1070:market-updated'].forEach(e=>window.addEventListener(e,()=>setTimeout(render,30)));document.addEventListener('DOMContentLoaded',()=>{render();setTimeout(render,1200);setTimeout(render,3500)});window.Bitcoin1070InvestmentOSUI={render,version:'16.1'};
})();
