// Bitcoin1070 PRO v16.2.1 - AI Commander UI
(()=>{'use strict';
const yen=v=>Number.isFinite(Number(v))?'¥'+Math.round(Number(v)).toLocaleString('ja-JP'):'--';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tradeReasons(r){const x=r.plan?.reasons;if(!x)return'';return `<div class="ios-trade-reasons"><span><b>買い候補の根拠：</b>${esc(x.buy)}</span><span><b>利確候補の根拠：</b>${esc(x.takeProfit)}</span><span><b>損切り候補の根拠：</b>${esc(x.stop)}</span>${Number.isFinite(Number(x.riskReward))?`<span><b>リスクリワード：</b>${Number(x.riskReward).toFixed(2)}</span>`:''}</div>`}
function riskAdvice(r){if(!r)return[];const a=r.allocation||{},out=[];if((a.cash??0)<5)out.push({title:'待機資金',text:'現金比率が5%未満。新規資金を現金として残すと急落時の選択肢が増えます。'});if(r.largest?.weight>=35)out.push({title:`${r.largest.symbol}集中`,text:`最大銘柄が${r.largest.weight}%。30%以下を目安にすると単一銘柄ショックへの依存を抑えられます。`});if((a.crypto??0)>=30)out.push({title:'暗号資産比率',text:`暗号資産${a.crypto}%。値動きが大きいため、市場急落シナリオへの寄与が高めです。`});return out.length?out.slice(0,3):[{title:'配分',text:'大きな単一要因は検出されていません。'}]}
function riskHTML(r){if(!r)return'';const a=r.allocation||{},sc=(r.scenarios||[]).map(s=>`<div class="ios-stress-row"><span>${esc(s.name)}</span><strong>-${Number(s.lossPct||0).toFixed(1)}%</strong></div>`).join('');return `<div class="ios-risk"><span>🛡️ ポートフォリオ耐久度</span><strong>${r.score}/100・${esc(r.label)}</strong><div class="ios-stress-list">${sc}</div><small>構成：暗号 ${a.crypto??0}% / 米国株 ${a.us??0}% / 日本株 ${a.jp??0}% / 現金 ${a.cash??0}%${r.largest?`・最大 ${esc(r.largest.symbol)} ${r.largest.weight}%`:''}</small><details><summary>なぜこの点数？・改善案</summary><div class="ios-reasons">${riskAdvice(r).map(x=>`<span><b>${esc(x.title)}</b> ${esc(x.text)}</span>`).join('')}</div></details><small>${esc(r.method||'ストレスシナリオによる参考評価')}</small></div>`}
function evidenceHTML(r){const e=r.evidence;if(!e)return'';return `<div class="ios-checks">${(e.checks||[]).map(x=>`<span>${x.ok?'✓':'△'} ${esc(x.name)}</span>`).join('')}</div><p><b>テクニカル確認:</b> ${e.positive}/${e.available}一致${e.strongReady?'・強気判定条件を満たす':e.weakReady?'・弱気判定条件を満たす':'・確定判定は保留'}</p>`}
function render(){const root=document.getElementById('investmentOSCommander'),api=window.Bitcoin1070InvestmentOS;if(!root||!api)return;const c=api.commander();if(!c){root.innerHTML='<div class="loading-state">AI司令塔の判断材料を取得中...</div>';return}const actions=c.actions||[];root.innerHTML=`<div class="ios-head"><div><span class="eyebrow">INVESTMENT OS</span><h2>🧠 AI司令塔</h2></div><div class="ios-quality"><small>データ品質</small><strong>${c.dataQuality}/100</strong></div></div><p class="ios-lead">今日優先して確認する判断を最大3件に絞ります。</p><div class="ios-actions">${actions.map((r,i)=>`<article class="ios-action"><div class="ios-rank">${i+1}</div><div class="ios-action-main"><div class="ios-action-title"><strong>${esc(r.asset.symbol)}</strong><span>${esc(r.action)}</span></div>${r.provisional?`<div class="ios-status-note">⚠️ ${esc(r.statusDetail)}。取得済みデータだけで計算した暫定値です。</div>`:`<div class="ios-status-note ios-status-ok">✓ ${esc(r.statusDetail)}</div>`}<div class="ios-scores"><span>総合 <b>${r.factor.score}/100</b></span><span>買い場 <b>${r.opportunity.score}/100</b></span><span>信頼度 <b>${r.confidence}/100</b></span></div>${r.plan?.available?`<div class="ios-levels"><span>買い候補 ${yen(r.plan.buyZone)}</span><span>利確候補 ${yen(r.plan.takeProfit1)}</span><span>損切り候補 ${yen(r.plan.stopLoss)}</span></div>${tradeReasons(r)}`:`<div class="ios-status-note">売買候補価格：テクニカル取得後に表示</div>`}<details><summary>判断根拠・データ品質</summary><div class="ios-reasons">${(r.factor.factors||[]).slice(0,6).map(f=>`<span>${esc(f.name)} ${Math.round(f.score)}/100</span>`).join('')}</div>${evidenceHTML(r)}<div class="ios-checks">${(r.quality.checks||[]).map(x=>`<span>${x.status==='live'?'✓':x.status==='stale'?'△':'×'} ${esc(x.name)}</span>`).join('')}</div>${r.missing?.length?`<p><b>不足データ:</b> ${r.missing.map(esc).join(' / ')}</p>`:''}${r.plan?.invalidation?.length?`<p><b>判断を撤回する条件:</b> ${r.plan.invalidation.map(esc).join(' / ')}</p>`:''}</details></div></article>`).join('')}</div>${riskHTML(c.risk)}<small class="ios-disclaimer">${esc(c.disclaimer)}</small>`}
['bitcoin1070:investment-os-ready','bitcoin1070:data-layer-updated','bitcoin1070:daily-changes-updated','bitcoin1070:professional-ai-updated','bitcoin1070:technical-autoload-complete','b1070:market-updated'].forEach(e=>window.addEventListener(e,()=>setTimeout(render,30)));document.addEventListener('DOMContentLoaded',()=>{render();setTimeout(render,1200);setTimeout(render,3500)});window.Bitcoin1070InvestmentOSUI={render,version:'16.2.1'};
})();