// Bitcoin1070 PRO v17.0 - investment utility engine
(()=>{'use strict';
const API='https://bitcoin1070-api.531unchi.workers.dev',SNAPSHOT_KEY='bitcoin1070_v17_asset_snapshots',MARKET_KEY='bitcoin1070_v17_market_cache';
const n=v=>{if(v===null||v===undefined||v==='')return null;const x=Number(v);return Number.isFinite(x)?x:null};
const assets=()=>typeof loadAssetsFromStorage==='function'?loadAssetsFromStorage(window.DEFAULT_ASSETS||[]):[];const cash=()=>typeof loadCashBalance==='function'?loadCashBalance():0;
async function json(url,ms=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function unitCostJpy(a,fx){if(typeof assetUnitCostJpy==='function')return assetUnitCostJpy(a);const c=n(a?.cost);if(c===null)return null;return a.type==='us'?c*(n(a.acquisitionUsdJpy)||fx||0):c}
function buySimulation({symbol,budgetJpy,price,usdJpy}){const a=assets().find(x=>String(x.symbol).toUpperCase()===String(symbol).toUpperCase());if(!a)return{ok:false,error:'銘柄が見つかりません'};const budget=n(budgetJpy),p=n(price),fx=a.type==='us'?n(usdJpy):1;if(!budget||budget<=0||!p||p<=0||(a.type==='us'&&(!fx||fx<=0)))return{ok:false,error:'金額・価格・為替を確認してください'};const unitJpy=p*fx,qty=budget/unitJpy,oldQty=n(a.amount)||0,oldCost=unitCostJpy(a,fx),newQty=oldQty+qty,newCost=oldCost===null?unitJpy:(oldCost*oldQty+budget)/newQty;return{ok:true,asset:a,purchaseQuantity:qty,newQuantity:newQty,newAverageCostJpy:newCost,budgetJpy:budget,unitPriceJpy:unitJpy,readOnly:true}}
function fxSimulation({usdJpy,usPrices={}}){const fx=n(usdJpy);if(!fx||fx<=0)return{ok:false,error:'ドル円を入力してください'};let usValue=0;const rows=assets().filter(a=>a.type==='us').map(a=>{const price=n(usPrices[a.symbol]);if(price===null)return{symbol:a.symbol,status:'missing',valueJpy:null};const valueJpy=(n(a.amount)||0)*price*fx;usValue+=valueJpy;return{symbol:a.symbol,status:'ok',valueJpy,priceUsd:price,usdJpy:fx}});return{ok:true,usdJpy:fx,usValueJpy:usValue,cashJpy:cash(),rows}}
function saveSnapshot(snapshot){const row={id:`${Date.now()}`,createdAt:new Date().toISOString(),...snapshot};let all=[];try{all=JSON.parse(localStorage.getItem(SNAPSHOT_KEY)||'[]');if(!Array.isArray(all))all=[]}catch(_){}all.unshift(row);all=all.slice(0,730);localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(all));return row}function snapshots(){try{const x=JSON.parse(localStorage.getItem(SNAPSHOT_KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}}function normalizedReturn(start,end){const s=n(start),e=n(end);return s&&e?(e/s-1)*100:null}
const defs=[['USDJPY','ドル円','USDJPY=X'],['NIKKEI','日経平均','^N225'],['NASDAQ','NASDAQ総合','^IXIC'],['SP500','S&P500','^GSPC'],['US10Y','米10年債利回り','^TNX'],['VIX','VIX','^VIX']];
async function yahoo(symbol){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?interval=1d&range=5d`;const d=await json(u);const r=d?.chart?.result?.[0],m=r?.meta||{},cl=r?.indicators?.quote?.[0]?.close||[],vals=cl.filter(x=>n(x)!==null),value=n(m.regularMarketPrice)??n(vals.at(-1)),prev=n(m.chartPreviousClose)??n(vals.at(-2));if(value===null)throw Error('missing');return{value,changePct:prev?((value/prev)-1)*100:null,updatedAt:m.regularMarketTime?m.regularMarketTime*1000:Date.now(),source:'Yahoo Finance'}}
async function btc(){let d;try{d=await json(`${API}?mode=crypto&ids=bitcoin&t=${Date.now()}`)}catch(_){d=await json('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=jpy&include_24hr_change=true')};const p=d?.prices?.bitcoin||d?.bitcoin||{},value=n(p.jpy),changePct=n(p.jpy_24h_change);if(value===null)throw Error('missing');return{value,changePct,updatedAt:Date.now(),source:d?.prices?'Bitcoin1070 API':'CoinGecko'}}
async function fear(){let d;try{d=await json(`${API}?mode=fear-greed&t=${Date.now()}`)}catch(_){d=await json('https://api.alternative.me/fng/?limit=1')};const value=n(d?.value??d?.data?.[0]?.value);if(value===null)throw Error('missing');return{value,changePct:null,label:String(d?.classification??d?.data?.[0]?.value_classification??''),updatedAt:Date.now(),source:d?.value!==undefined?'Bitcoin1070 API':'Alternative.me'}}
async function marketIndicators(){const jobs=defs.map(async([key,label,symbol])=>{try{return{key,label,status:'live',...(await yahoo(symbol))}}catch(e){return{key,label,status:'missing',value:null,changePct:null,updatedAt:null,source:'Yahoo Finance'}}});jobs.push(btc().then(x=>({key:'BTC',label:'BTC',status:'live',...x})).catch(()=>({key:'BTC',label:'BTC',status:'missing',value:null,changePct:null,updatedAt:null,source:null})));jobs.push(fear().then(x=>({key:'FEAR',label:'Fear & Greed',status:'live',...x})).catch(()=>({key:'FEAR',label:'Fear & Greed',status:'missing',value:null,changePct:null,updatedAt:null,source:null})));const rows=await Promise.all(jobs),live=rows.filter(x=>x.status==='live').length,result={rows,quality:Math.round(live/rows.length*100),observedAt:Date.now()};try{localStorage.setItem(MARKET_KEY,JSON.stringify(result))}catch(_){}return result}
function investmentCalendar(){const year=new Date().getFullYear(),events=[{date:'2028-04-20',title:'BTC 次回半減期（想定）',importance:'高',assets:['BTC','暗号資産'],kind:'cycle',note:'ネットワーク状況で実日付は前後します'}];return{year,events,source:'固定日を捏造しないため、経済統計/FOMC/日銀/決算は外部カレンダーAPI接続まで未取得表示',updatedAt:Date.now()}}
window.Bitcoin1070InvestmentTools={buySimulation,fxSimulation,saveSnapshot,snapshots,normalizedReturn,marketIndicators,investmentCalendar,keys:{snapshots:SNAPSHOT_KEY,market:MARKET_KEY},version:'17.0'};
})();