// Bitcoin1070 PRO v15.0 - Professional multi-factor decision engine
(()=>{'use strict';
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));const num=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null};const center=()=>window.Bitcoin1070DecisionCenter;
const daily=()=>{for(const k of ['bitcoin1070_daily_changes_v14_0','bitcoin1070_daily_changes_v13_1']){try{const x=JSON.parse(localStorage.getItem(k)||'null');if(x?.values)return x.values}catch(_){}}return{}};
const technical=new Map();const techKey=a=>`${a?.type||''}:${String(a?.symbol||'').trim().toUpperCase()}`;
function ingestTechnical(result){if(!result?.asset)return;technical.set(techKey(result.asset),{...result,observedAt:Date.now()});window.dispatchEvent(new CustomEvent('bitcoin1070:professional-ai-updated'));}
function getTechnical(asset){const row=technical.get(techKey(asset));return row&&Date.now()-row.observedAt<6*60*60*1000?row:null;}
function confidence(factors){const used=factors.reduce((s,f)=>s+f.weight,0),coverage=Math.min(1,used);if(!factors.length)return{score:10,label:'低',coverage:0};const vals=factors.map(f=>f.score),spread=Math.max(...vals)-Math.min(...vals),agreement=clamp(1-spread/100,0,1);const stale=factors.some(f=>f.stale)?-.12:0;const score=clamp(Math.round((coverage*.62+agreement*.38+stale)*100));return{score,label:score>=80?'高':score>=60?'中':'低',coverage:Math.round(coverage*100)};}
function factorScore(asset){const api=center();if(!api)return null;const row=daily()[api.keyOf(asset)]||{},ch=num(row.percent),factors=[];
 if(ch!==null)factors.push({name:asset.type==='crypto'?'24hモメンタム':'前日モメンタム',score:clamp(50+ch*6),weight:.16,value:ch});
 const p=api.priceOf(asset),cost=num(asset.averagePrice??asset.avgPrice??asset.costPrice??asset.purchasePrice);if(p!==null&&cost!==null&&cost>0){const ret=(p/cost-1)*100;factors.push({name:'取得価格乖離',score:clamp(50+ret*.45),weight:.10,value:ret});}
 const t=getTechnical(asset);if(t){factors.push({name:'テクニカル総合',score:clamp(num(t.score)??50),weight:.34,value:t.score});const rr=num(t.tradeLevels?.riskReward);if(rr!==null)factors.push({name:'リスクリワード',score:clamp(35+rr*22),weight:.12,value:rr});const rsi=num(t.rsi);if(rsi!==null){const rsiScore=rsi>75?25:rsi>70?38:rsi<25?45:rsi<35?58:rsi>=45&&rsi<=65?68:55;factors.push({name:'RSI状態',score:rsiScore,weight:.08,value:rsi});}}
 const h=api.health();if(h?.score!==null)factors.push({name:'ポートフォリオ健全性',score:h.score,weight:.08,value:h.score});
 let cycle=null;try{cycle=window.Bitcoin1070Cycle?.snapshot?.()}catch(_){}if(asset.type==='crypto'&&String(asset.symbol).toUpperCase()==='BTC'&&cycle){const progress=num(cycle.progress);let cycleScore=50;if(cycle.stage==='底候補ゾーン')cycleScore=78;else if(cycle.stage==='次サイクル上昇期')cycleScore=progress<70?75:62;else if(cycle.stage==='次回ピーク候補')cycleScore=28;else if(cycle.stage==='下落・底探し')cycleScore=38;factors.push({name:'1070日サイクル',score:cycleScore,weight:.12,value:progress});}
 const used=factors.reduce((s,f)=>s+f.weight,0);if(!used)return{score:50,confidence:{score:10,label:'低',coverage:0},factors:[],label:'データ不足'};const score=clamp(Math.round(factors.reduce((s,f)=>s+f.score*f.weight,0)/used)),conf=confidence(factors);return{score,confidence:conf,factors,label:score>=72?'強気':score<=34?'弱気':'中立',technical:t};}
function crashRadar(asset){const api=center(),ch=num(daily()[api.keyOf(asset)]?.percent),base=factorScore(asset),t=base?.technical;let opportunity=45;const reasons=[];if(ch!==null){if(ch<=-10){opportunity+=18;reasons.push('急落率が大きい')}else if(ch<=-6){opportunity+=13;reasons.push('強い下落')}else if(ch<=-3){opportunity+=7;reasons.push('押し目候補')}else if(ch>6){opportunity-=12;reasons.push('短期過熱')}}if(t){const rsi=num(t.rsi),pos=num(t.bollinger?.position),support=num(t.levels?.support),price=num(t.currentPrice);if(rsi!==null&&rsi<=35){opportunity+=12;reasons.push('RSI低位')}if(pos!==null&&pos<=20){opportunity+=8;reasons.push('BB下側')}if(support&&price&&Math.abs(price-support)/price<=.04){opportunity+=10;reasons.push('支持線が近い')}if(num(t.score)>=65){opportunity+=8;reasons.push('テクニカル反転余地')}if(num(t.score)<=35){opportunity-=12;reasons.push('下降トレンド継続リスク')}}else opportunity-=8;if(base?.confidence.score<50)opportunity-=8;opportunity=clamp(Math.round(opportunity));return{score:opportunity,label:opportunity>=78?'暴落買い候補':opportunity>=65?'強い押し目':opportunity>=55?'押し目監視':'通常',reasons,confidence:base?.confidence||{score:10,label:'低'}};}
function anomaly(asset){const api=center(),ch=num(daily()[api.keyOf(asset)]?.percent),t=getTechnical(asset);if(ch===null)return{level:'unknown',score:0,label:'データ不足'};let score=Math.abs(ch)*9;const vr=num(t?.volume?.ratio);if(vr!==null&&vr>=1.8)score+=18;if(vr!==null&&vr>=2.5)score+=10;score=clamp(Math.round(score));return{score,level:score>=80?'high':score>=55?'medium':'normal',label:score>=80?'異常変動':score>=55?'要監視':'通常範囲',reason:`${asset.type==='crypto'?'24時間':'前日'} ${ch>=0?'+':''}${ch.toFixed(2)}%${vr!==null?`・出来高 ${vr.toFixed(1)}倍`:''}`};}
function commander(){const api=center();if(!api)return null;const rows=api.holdings().map(asset=>({asset,model:factorScore(asset),crash:crashRadar(asset),anomaly:anomaly(asset)}));const urgent=rows.filter(x=>x.anomaly.level==='high'),opportunities=rows.filter(x=>x.crash.score>=65&&x.crash.confidence.score>=55).sort((a,b)=>b.crash.score-a.crash.score),weak=rows.filter(x=>x.model?.score<=34&&x.model.confidence.score>=55),actions=[];if(urgent.length)actions.push({priority:1,title:'異常値動きを確認',text:urgent.slice(0,3).map(x=>x.asset.symbol).join('・')+' は値幅と出来高を再確認'});if(opportunities.length)actions.push({priority:2,title:'押し目候補を精査',text:`${opportunities[0].asset.symbol} 買い場 ${opportunities[0].crash.score}/100・信頼度 ${opportunities[0].crash.confidence.label}`});if(weak.length)actions.push({priority:3,title:'弱気銘柄を点検',text:weak.slice(0,3).map(x=>x.asset.symbol).join('・')+' は撤退条件と支持線を確認'});if(!actions.length)actions.push({priority:5,title:'無理に売買しない',text:'高信頼度で緊急性のあるシグナルは未検出'});return{rows,actions:actions.sort((a,b)=>a.priority-b.priority).slice(0,3),health:api.health()};}
function simulateCapital(amount){const c=commander(),cash=Math.max(0,num(amount)||0);if(!c)return[];const eligible=c.rows.filter(x=>x.model?.confidence.score>=60&&x.model.score>=48&&x.crash.score>=50).sort((a,b)=>(b.model.score*.55+b.crash.score*.45)-(a.model.score*.55+a.crash.score*.45)).slice(0,4);const raw=eligible.map(x=>Math.max(1,(x.model.score*.55+x.crash.score*.45)-45)*(x.model.confidence.score/100)),total=raw.reduce((a,b)=>a+b,0)||1;return eligible.map((x,i)=>({symbol:x.asset.symbol,allocation:Math.round(cash*raw[i]/total),weight:raw[i]/total,score:x.model.score,opportunity:x.crash.score,confidence:x.model.confidence}));}
window.Bitcoin1070ProfessionalAI={factorScore,crashRadar,anomaly,commander,simulateCapital,ingestTechnical,getTechnical,version:'15.0'};window.dispatchEvent(new CustomEvent('bitcoin1070:professional-ai-ready'));})();
