// Bitcoin1070 PRO Service Worker v16.5 build2
const CACHE_NAME='bitcoin1070-pro-v16-5-build2';
const CORE_FILES=['./','./index.html','./cycle1070.html','./settings.html','./analytics-dashboard.html','./style.css?v=15.0','./app-shell.js?v=16.5','./analytics-tracker.js?v=16.4','./cloud-analytics.js?v=16.5','./analytics-cloud-status.js?v=16.5','./analytics-dashboard.js?v=16.4','./manifest.json?v=16.3.1','./icon-192.png','./icon-512.png'];
const OPTIONAL_FILES=['./portfolio.html','./market.html','./analysis.html','./portfolio-edit.html','./asset-intelligence.html','./future-simulator.html','./investment-os-data.js?v=16.2.1','./professional-ai.js?v=16.2.1','./investment-os.js?v=16.2.1','./investment-os-ui.js?v=16.2.1','./btc1070-intelligence.js?v=16.3.1'];
const FORCED=new Map([['/app-shell.js','./app-shell.js?v=16.5'],['/analytics-tracker.js','./analytics-tracker.js?v=16.4'],['/cloud-analytics.js','./cloud-analytics.js?v=16.5'],['/analytics-cloud-status.js','./analytics-cloud-status.js?v=16.5'],['/analytics-dashboard.js','./analytics-dashboard.js?v=16.4'],['/investment-os-data.js','./investment-os-data.js?v=16.2.1'],['/professional-ai.js','./professional-ai.js?v=16.2.1'],['/investment-os.js','./investment-os.js?v=16.2.1'],['/investment-os-ui.js','./investment-os-ui.js?v=16.2.1'],['/btc1070-intelligence.js','./btc1070-intelligence.js?v=16.3.1']]);
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE_NAME);await cache.addAll(CORE_FILES);await Promise.allSettled(OPTIONAL_FILES.map(file=>cache.add(file)));await self.skipWaiting()})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)));await self.clients.claim()})()));
self.addEventListener('message',event=>{if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(url.origin!==location.origin)return;const forced=FORCED.get(url.pathname.slice(url.pathname.lastIndexOf('/')));if(forced){event.respondWith((async()=>{const cache=await caches.open(CACHE_NAME);try{const fresh=await fetch(forced,{cache:'reload'});if(fresh.ok)await cache.put(forced,fresh.clone());return fresh}catch(_){return(await cache.match(forced))||Response.error()}})());return}if(event.request.mode==='navigate'){event.respondWith((async()=>{try{const fresh=await fetch(event.request,{cache:'no-store'});const cache=await caches.open(CACHE_NAME);if(fresh.ok)await cache.put(event.request,fresh.clone());return fresh}catch(_){return(await caches.match(event.request))||(await caches.match('./index.html'))}})());return}event.respondWith((async()=>{const cached=await caches.match(event.request);if(cached)return cached;try{const fresh=await fetch(event.request);if(fresh.ok){const cache=await caches.open(CACHE_NAME);await cache.put(event.request,fresh.clone())}return fresh}catch(_){return Response.error()}})())});
