// Technical Analysis Engine v15 bridge
// Existing calculation functions are intentionally kept globally accessible.
const TECHNICAL_SYMBOL_MAP={BTC:'BTC-USD',ETH:'ETH-USD',XRP:'XRP-USD',SOL:'SOL-USD',SUI:'SUI20947-USD',RENDER:'RENDER-USD',NVDA:'NVDA',MHI:'7011.T',ADVT:'6857.T',FJK:'5803.T',VRAIN:'135A.T'};
let technicalAnalysisRunning=false;
const technicalClamp=(v,a,b)=>Math.min(b,Math.max(a,v));const technicalRound=(v,d=2)=>Number.isFinite(Number(v))?Number(Number(v).toFixed(d)):0;
function getTechnicalYahooSymbol(asset){return String(asset.yahooSymbol||'').trim()||TECHNICAL_SYMBOL_MAP[String(asset.symbol||'').toUpperCase()]||''}
function calculateSMA(v,p){if(!Array.isArray(v)||v.length<p)return null;return v.slice(-p).reduce((s,x)=>s+Number(x),0)/p}
function calculateEMAArray(v,p){if(v.length<p)return[];const k=2/(p+1),out=[];let prev=v.slice(0,p).reduce((s,x)=>s+Number(x),0)/p;for(let i=0;i<v.length;i++){if(i<p-1)out.push(null);else if(i===p-1)out.push(prev);else{prev=Number(v[i])*k+prev*(1-k);out.push(prev)}}return out}
function calculateMACD(closes){const e12=calculateEMAArray(closes,12),e26=calculateEMAArray(closes,26),line=closes.map((_,i)=>e12[i]!=null&&e26[i]!=null?e12[i]-e26[i]:null),valid=line.filter(x=>x!=null),sigCompact=calculateEMAArray(valid,9),sig=Array(line.length).fill(null);let j=0;line.forEach((x,i)=>{if(x!=null)sig[i]=sigCompact[j++]??null});const idx=line.map((x,i)=>({x,i})).filter(o=>o.x!=null&&sig[o.i]!=null);if(idx.length<2)return{macd:0,signal:0,histogram:0,cross:'none'};const a=idx.at(-1).i,b=idx.at(-2).i;let cross='none';if(line[b]<=sig[b]&&line[a]>sig[a])cross='golden';if(line[b]>=sig[b]&&line[a]<sig[a])cross='dead';return{macd:technicalRound(line[a],4),signal:technicalRound(sig[a],4),histogram:technicalRound(line[a]-sig[a],4),cross}}
function calculateRSI(c,p=14){if(c.length<=p)return 50;const d=c.slice(-(p+1)).slice(1).map((x,i)=>x-c.slice(-(p+1))[i]);const g=d.reduce((s,x)=>s+Math.max(0,x),0)/p,l=d.reduce((s,x)=>s+Math.max(0,-x),0)/p;if(!l)return 100;return technicalRound(100-100/(1+g/l),2)}
function calculateVolumeAnalysis(v){const x=v.map(Number).filter(Number.isFinite);if(x.length<20)return{latest:x.at(-1)||0,average20:0,ratio:1};const avg=x.slice(-20).reduce((a,b)=>a+b,0)/20;return{latest:x.at(-1),average20:avg,ratio:avg?technicalRound(x.at(-1)/avg,2):1}}
function calculateStdDev(v){const m=v.reduce((a,b)=>a+b,0)/v.length;return Math.sqrt(v.reduce((s,x)=>s+(x-m)**2,0)/v.length)}
function calculateBollingerBands(c,p=20,m=2){const x=c.slice(-p);if(x.length<p)return{middle:0,upper:0,lower:0,bandwidth:0,position:50};const mid=x.reduce((a,b)=>a+b,0)/p,sd=calculateStdDev(x),u=mid+sd*m,l=mid-sd*m;return{middle:technicalRound(mid),upper:technicalRound(u),lower:technicalRound(l),bandwidth:mid?technicalRound((u-l)/mid*100):0,position:u>l?technicalRound((c.at(-1)-l)/(u-l)*100,1):50}}
function calculateATR(c,p=14){if(c.length<=p)return 0;const r=[];for(let i=1;i<c.length;i++)r.push(Math.max(Number(c[i].high)-Number(c[i].low),Math.abs(Number(c[i].high)-Number(c[i-1].close)),Math.abs(Number(c[i].low)-Number(c[i-1].close))));return r.slice(-p).reduce((a,b)=>a+b,0)/p}
function calculateSupportResistance(c,price){const r=c.slice(-120),lows=r.map(x=>Number(x.low)).filter(x=>x<price).sort((a,b)=>b-a),highs=r.map(x=>Number(x.high)).filter(x=>x>price).sort((a,b)=>a-b);return{support:technicalRound(lows[0]??price),resistance:technicalRound(highs[0]??price)}}
function calculate52WeekRange(c,price){const y=c.slice(-260),h=Math.max(...y.map(x=>Number(x.high)||Number(x.close))),l=Math.min(...y.map(x=>Number(x.low)||Number(x.close)));return{high:technicalRound(h),low:technicalRound(l),fromHigh:h?technicalRound((price-h)/h*100,1):0,fromLow:l?technicalRound((price-l)/l*100,1):0,position:h>l?technicalRound((price-l)/(h-l)*100,1):50}}
function calculateTradeLevels(price,atr,levels){const a=atr||price*.025,stop=Math.max(0,Math.min(price*.99,Math.max(price-a*1.5,levels.support*.985))),t1=Math.max(price+a*1.5,levels.resistance),t2=Math.max(price+a*3,t1+a),risk=price-stop;return{takeProfit1:technicalRound(t1),takeProfit2:technicalRound(t2),stopLoss:technicalRound(stop),riskReward:risk?technicalRound((t1-price)/risk):0}}
function calculateTechnicalScore(d){let s=50,r=[],w=[];const add=(n,t)=>{s+=n;r.push(t)},sub=(n,t)=>{s-=n;w.push(t)};if(d.ma5>d.ma25&&d.ma25>d.ma75)add(14,'移動平均線が上昇配列');else if(d.ma5<d.ma25&&d.ma25<d.ma75)sub(14,'移動平均線が下降配列');if(d.currentPrice>d.ma25)add(6,'価格が25日線より上');else sub(6,'価格が25日線より下');if(d.macd.cross==='golden')add(12,'MACDゴールデンクロス');else if(d.macd.cross==='dead')sub(12,'MACDデッドクロス');else if(d.macd.macd>d.macd.signal)add(5,'MACDがシグナルより上');else sub(5,'MACDがシグナルより下');if(d.rsi>=45&&d.rsi<=65)add(5,'RSIが健全');if(d.rsi>=75)sub(9,'RSIが強い買われすぎ');else if(d.rsi>=70)sub(5,'RSIが買われすぎ');if(d.volume.ratio>=1.3&&d.priceChange>=0)add(6,'上昇を伴う出来高増加');if(d.volume.ratio>=1.3&&d.priceChange<0)sub(6,'下落を伴う出来高増加');if(d.bollinger.position>100)sub(5,'BB上限超え');if(d.week52.position>=70&&d.week52.position<95)add(7,'52週レンジ上位');if(d.week52.position<=20)sub(5,'52週安値圏');if(d.tradeLevels.riskReward>=1.5)add(5,'リスクリワード良好');else if(d.tradeLevels.riskReward<1)sub(5,'リスクリワード低い');s=technicalClamp(Math.round(s),0,100);return{score:s,judgment:s>=80?'強い買い寄り':s>=65?'買い寄り':s<=20?'強い売り寄り':s<=35?'売り寄り':'中立',reasons:r.slice(0,6),warnings:w.slice(0,6)}}
async function analyzeTechnicalAsset(asset){const symbol=getTechnicalYahooSymbol(asset);if(!symbol)throw new Error('Yahoo Financeコード未設定');const response=await fetch(`${STOCK_API_URL}?mode=history&symbol=${encodeURIComponent(symbol)}&t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();if(data.error||!Array.isArray(data.candles))throw new Error(data.message||data.error||'データ取得失敗');const candles=data.candles.filter(x=>Number.isFinite(Number(x.close)));if(candles.length<80)throw new Error('分析用データが不足');const closes=candles.map(x=>Number(x.close)),volumes=candles.map(x=>Number(x.volume)||0),currentPrice=closes.at(-1),previous=closes.at(-2);const analysis={asset,yahooSymbol:symbol,currentPrice,priceChange:previous?technicalRound((currentPrice-previous)/previous*100):0,ma5:technicalRound(calculateSMA(closes,5)),ma25:technicalRound(calculateSMA(closes,25)),ma75:technicalRound(calculateSMA(closes,75)),rsi:calculateRSI(closes),macd:calculateMACD(closes),volume:calculateVolumeAnalysis(volumes)};analysis.bollinger=calculateBollingerBands(closes);analysis.atr=technicalRound(calculateATR(candles));analysis.levels=calculateSupportResistance(candles,currentPrice);analysis.week52=calculate52WeekRange(candles,currentPrice);analysis.tradeLevels=calculateTradeLevels(currentPrice,analysis.atr,analysis.levels);const result={...analysis,...calculateTechnicalScore(analysis)};window.Bitcoin1070ProfessionalAI?.ingestTechnical?.(result);return result}
function getTechnicalJudgmentClass(s){return s>=60?'profit-positive':s<=40?'profit-negative':'profit-neutral'}
function renderTechnicalResult(r){return `<div class="asset-card technical-card"><div class="asset-card-header"><div><strong>${r.asset.name}</strong><span class="asset-symbol">${r.asset.symbol}</span></div></div><div class="asset-row"><span>参考スコア</span><strong class="${getTechnicalJudgmentClass(r.score)}">${r.score}点 ／ ${r.judgment}</strong></div><div class="asset-row"><span>RSI</span><strong>${r.rsi}</strong></div><div class="asset-row"><span>MACD</span><strong>${r.macd.cross==='golden'?'🟢 ゴールデン':r.macd.cross==='dead'?'🔴 デッド':r.macd.macd>r.macd.signal?'🟢 上向き':'🔴 下向き'}</strong></div><div class="asset-row"><span>サポート / レジスタンス</span><strong>${r.levels.support} / ${r.levels.resistance}</strong></div><div class="asset-row"><span>利確① / 損切り</span><strong>${r.tradeLevels.takeProfit1} / ${r.tradeLevels.stopLoss}</strong></div><p class="technical-disclaimer">ATR・出来高・トレンド・サポレジを統合した参考値です。</p></div>`}
function renderTechnicalError(a,e){return `<div class="asset-card"><strong>${a.name}（${a.symbol}）</strong><p class="profit-negative">分析失敗：${e.message}</p></div>`}
async function analyzeAllTechnicalAssets(){if(technicalAnalysisRunning)return;const container=document.getElementById('technicalAnalysisList'),button=document.getElementById('technicalAnalysisBtn');if(!container)return;technicalAnalysisRunning=true;if(button){button.disabled=true;button.textContent='分析中...'}const results=[],signals=[];for(const asset of assets){try{container.textContent=`${asset.name}を分析中...`;const r=await analyzeTechnicalAsset(asset);signals.push(r);results.push(renderTechnicalResult(r))}catch(e){results.push(renderTechnicalError(asset,e))}}container.innerHTML=results.join('');if(typeof updateSignalDashboard==='function')updateSignalDashboard(signals);technicalAnalysisRunning=false;if(button){button.disabled=false;button.textContent='🔄 分析を更新'}}
document.addEventListener('DOMContentLoaded',()=>document.getElementById('technicalAnalysisBtn')?.addEventListener('click',analyzeAllTechnicalAssets));
