// Bitcoin1070 PRO v12.3 - transaction ledger UI
const ledgerForm=document.getElementById("ledgerForm"),kindInput=document.getElementById("ledgerKind"),typeInput=document.getElementById("tradeType");
const yen=value=>`¥${Math.round(Number(value)||0).toLocaleString("ja-JP")}`;
const number=value=>Number(value).toLocaleString("ja-JP",{maximumFractionDigits:8});
function localDateValue(){const now=new Date(),offset=now.getTimezoneOffset()*60000;return new Date(now-offset).toISOString().slice(0,16);}
function currentAssets(){return loadAssetsFromStorage([]);}
function updateAssetOptions(){
  const type=typeInput.value,list=document.getElementById("assetSymbols"),items=[...currentAssets(),...(Array.isArray(window.B1070_ASSET_MASTER)?window.B1070_ASSET_MASTER:[])].filter(a=>a.type===type),seen=new Set();list.replaceChildren();
  items.forEach(asset=>{const key=String(asset.symbol).toUpperCase();if(seen.has(key))return;seen.add(key);const option=document.createElement("option");option.value=asset.symbol;option.label=asset.name;list.append(option);});
}
function selectedAsset(){const symbol=document.getElementById("tradeSymbol").value.trim().toUpperCase();return [...currentAssets(),...(window.B1070_ASSET_MASTER||[])].find(a=>a.type===typeInput.value&&String(a.symbol).toUpperCase()===symbol);}
function fillAsset(){const asset=selectedAsset();if(asset)document.getElementById("tradeName").value=asset.name||"";}
function renderMode(){
  const kind=kindInput.value,isTrade=kind==="BUY"||kind==="SELL";document.querySelectorAll(".trade-only").forEach(el=>el.classList.toggle("hidden",!isTrade));document.getElementById("assetTypeLabel").classList.toggle("hidden",!isTrade);document.getElementById("cashAmountField").classList.toggle("hidden",isTrade);document.getElementById("fxField").classList.toggle("hidden",!isTrade||typeInput.value!=="us");document.getElementById("priceUnit").textContent=typeInput.value==="us"?"米ドル":"円";estimate();
}
function estimate(){const kind=kindInput.value,q=Number(document.getElementById("tradeQuantity").value),p=Number(document.getElementById("tradePrice").value),fx=typeInput.value==="us"?Number(document.getElementById("tradeFx").value):1,fee=Number(document.getElementById("tradeFee").value)||0,amount=Number(document.getElementById("cashAmount").value);let total;if(kind==="BUY")total=q*p*fx+fee;else if(kind==="SELL")total=q*p*fx-fee;else total=amount;document.getElementById("ledgerEstimate").textContent=total>0?`日本円増減: ${kind==="BUY"||kind==="WITHDRAWAL"?"−":"＋"}${yen(total)}`:"";}
function render(){
  document.getElementById("ledgerCash").textContent=yen(loadCashBalance());const container=document.getElementById("ledgerHistory"),items=loadTransactionsFromStorage();if(!items.length){container.innerHTML='<div class="empty-holdings-state"><strong>取引履歴はまだありません</strong><p>買付・売却・入出金を登録するとここに表示されます。</p></div>';return;}
  container.replaceChildren(...items.map(item=>{const row=document.createElement("article");row.className=`ledger-row ledger-${item.kind.toLowerCase()}`;const head=document.createElement("div"),badge=document.createElement("b"),date=document.createElement("time");badge.textContent=item.kind;date.textContent=new Date(item.date).toLocaleString("ja-JP");head.append(badge,date);const title=document.createElement("strong");title.textContent=item.symbol?`${item.name}（${item.symbol}）`:item.kind==="DEPOSIT"?"日本円 入金":"日本円 出金";const detail=document.createElement("p");if(item.symbol){const signed=item.kind==="SELL"?"−":"＋";detail.textContent=`${signed}${number(item.quantity)} ${item.type==="crypto"?item.symbol:"株"} / ${item.type==="us"?"$":"¥"}${number(item.unitPrice)} / ${item.cashDelta>=0?"＋":"−"}${yen(Math.abs(item.cashDelta))}`;}else detail.textContent=`${item.cashDelta>=0?"＋":"−"}${yen(Math.abs(item.cashDelta))}`;row.append(head,title,detail);return row;}));
}
document.querySelectorAll("[data-kind]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-kind]").forEach(b=>b.classList.remove("active"));button.classList.add("active");kindInput.value=button.dataset.kind;renderMode();}));
typeInput.addEventListener("change",()=>{updateAssetOptions();renderMode();});document.getElementById("tradeSymbol").addEventListener("change",fillAsset);ledgerForm.addEventListener("input",estimate);
ledgerForm.addEventListener("submit",event=>{event.preventDefault();const error=document.getElementById("ledgerError");error.textContent="";const asset=selectedAsset();try{commitLedgerTransaction({kind:kindInput.value,date:document.getElementById("tradeDate").value,type:typeInput.value,symbol:document.getElementById("tradeSymbol").value,name:document.getElementById("tradeName").value,quantity:document.getElementById("tradeQuantity").value,unitPrice:document.getElementById("tradePrice").value,fxRate:document.getElementById("tradeFx").value,feeJpy:document.getElementById("tradeFee").value,amount:document.getElementById("cashAmount").value,coinGeckoId:asset?.coinGeckoId,yahooSymbol:asset?.yahooSymbol});ledgerForm.reset();kindInput.value=document.querySelector("[data-kind].active").dataset.kind;document.getElementById("tradeDate").value=localDateValue();typeInput.value="jp";updateAssetOptions();renderMode();render();}catch(e){error.textContent=e.message;}});
document.getElementById("tradeDate").value=localDateValue();updateAssetOptions();renderMode();render();
