// Bitcoin1070 PRO v13.1 - transaction ledger UI / autocomplete
const ledgerForm=document.getElementById("ledgerForm"),kindInput=document.getElementById("ledgerKind"),typeInput=document.getElementById("tradeType"),searchInput=document.getElementById("tradeAssetSearch"),suggestions=document.getElementById("tradeAssetSuggestions");
const yen=value=>`¥${Math.round(Number(value)||0).toLocaleString("ja-JP")}`;
const number=value=>Number(value).toLocaleString("ja-JP",{maximumFractionDigits:8});
const signedYen=value=>`${Number(value)>=0?"＋":"−"}${yen(Math.abs(Number(value)))}`;
function setPnl(element,value){element.textContent=signedYen(value);element.className=value>0?"profit-positive":value<0?"profit-negative":"profit-neutral";}
let chosenAsset=null,searchTimer=null,searchController=null;
function localDateValue(){const now=new Date(),offset=now.getTimezoneOffset()*60000;return new Date(now-offset).toISOString().slice(0,16);}
function currentAssets(){return loadAssetsFromStorage([]);}
function clearSelection(clearQuery=false){chosenAsset=null;document.getElementById("tradeSymbol").value="";document.getElementById("tradeName").value="";document.getElementById("selectedTradeAsset").classList.add("hidden");if(clearQuery)searchInput.value="";}
function chooseAsset(asset){
  chosenAsset=asset;typeInput.value=asset.type;document.getElementById("tradeSymbol").value=asset.symbol;document.getElementById("tradeName").value=asset.name;searchInput.value="";suggestions.classList.add("hidden");searchInput.setAttribute("aria-expanded","false");
  const card=document.getElementById("selectedTradeAsset"),held=currentAssets().find(a=>a.type===asset.type&&String(a.symbol).toUpperCase()===asset.symbol);card.replaceChildren();
  const text=document.createElement("div"),title=document.createElement("strong"),meta=document.createElement("span"),remove=document.createElement("button");title.textContent=asset.name;meta.textContent=`${asset.symbol} ・ ${B1070AssetSearch.typeLabel(asset.type)}${kindInput.value==="SELL"?` ・ 保有 ${number(held?.amount||0)}`:""}`;text.append(title,meta);remove.type="button";remove.textContent="変更";remove.addEventListener("click",()=>{clearSelection(true);searchInput.focus();});card.append(text,remove);card.classList.remove("hidden");renderMode();
}
function renderSuggestions(items,offline=false){
  suggestions.replaceChildren();if(!items.length){const empty=document.createElement("div");empty.className="empty-suggestion";empty.textContent=offline?"通信できません。保有銘柄・端末内カタログにも一致がありません。":"候補が見つかりません。";suggestions.append(empty);}
  items.forEach(asset=>{const button=document.createElement("button"),symbol=document.createElement("strong"),name=document.createElement("span"),type=document.createElement("small");button.type="button";button.className="asset-suggestion";button.setAttribute("role","option");symbol.textContent=asset.symbol;name.textContent=asset.name;type.textContent=B1070AssetSearch.typeLabel(asset.type);button.append(symbol,name,type);button.addEventListener("click",()=>chooseAsset(asset));suggestions.append(button);});
  if(offline&&items.length){const note=document.createElement("div");note.className="empty-suggestion";note.textContent="オフライン候補を表示中";suggestions.append(note);}suggestions.classList.remove("hidden");searchInput.setAttribute("aria-expanded","true");
}
async function runSearch(){
  const query=searchInput.value;if(!query.trim()){suggestions.classList.add("hidden");return;}searchController?.abort();searchController=new AbortController();
  const result=await B1070AssetSearch.search(query,{holdings:currentAssets(),sellOnly:kindInput.value==="SELL",signal:searchController.signal});renderSuggestions(result.items,result.offline);
}
function queueSearch(){clearSelection();clearTimeout(searchTimer);searchTimer=setTimeout(()=>runSearch().catch(error=>{if(error.name!=="AbortError")renderSuggestions([],true);}),180);}
function renderMode(){
  const kind=kindInput.value,isTrade=kind==="BUY"||kind==="SELL";document.querySelectorAll(".trade-only").forEach(el=>el.classList.toggle("hidden",!isTrade||(el.id==="selectedTradeAsset"&&!chosenAsset)));document.getElementById("assetTypeLabel").classList.toggle("hidden",!isTrade);document.getElementById("cashAmountField").classList.toggle("hidden",isTrade);document.getElementById("fxField").classList.toggle("hidden",!isTrade||typeInput.value!=="us");document.getElementById("priceUnit").textContent=typeInput.value==="us"?"米ドル":"円";searchInput.placeholder=kind==="SELL"?"保有銘柄を検索":"285A / きおくしあ / NVDA / Bitcoin";estimate();
}
function estimate(){const kind=kindInput.value,q=Number(document.getElementById("tradeQuantity").value),p=Number(document.getElementById("tradePrice").value),fx=typeInput.value==="us"?Number(document.getElementById("tradeFx").value):1,fee=Number(document.getElementById("tradeFee").value)||0,amount=Number(document.getElementById("cashAmount").value);let total;if(kind==="BUY")total=q*p*fx+fee;else if(kind==="SELL")total=q*p*fx-fee;else total=amount;document.getElementById("ledgerEstimate").textContent=total>0?`日本円増減: ${kind==="BUY"||kind==="WITHDRAWAL"?"−":"＋"}${yen(total)}`:"";}
function renderRealized(items){
  const summary=summarizeRealizedPnl(items),year=document.getElementById("ledgerRealizedYear"),total=document.getElementById("ledgerRealizedTotal"),assets=document.getElementById("realizedByAsset");setPnl(year,summary.yearPnlJpy);setPnl(total,summary.totalPnlJpy);document.getElementById("ledgerRealizedYearLabel").textContent=`${summary.year}年`;document.getElementById("ledgerYearSellCount").textContent=`売却 ${summary.yearSellCount}回`;document.getElementById("ledgerSellCount").textContent=`売却 ${summary.sellCount}回`;
  if(!summary.byAsset.length){assets.replaceChildren();const empty=document.createElement("p");empty.className="small";empty.textContent="売却履歴はまだありません。";assets.append(empty);return;}
  assets.replaceChildren(...summary.byAsset.map(item=>{const row=document.createElement("div"),identity=document.createElement("div"),name=document.createElement("strong"),meta=document.createElement("small"),values=document.createElement("div"),totalValue=document.createElement("span"),yearValue=document.createElement("small");row.className="realized-asset-row";name.textContent=`${item.name}（${item.symbol}）`;meta.textContent=`売却 ${item.sellCount}回${item.unavailableCount?` ・ 算出不可 ${item.unavailableCount}回`:""}`;identity.append(name,meta);values.className="realized-asset-values";setPnl(totalValue,item.totalPnlJpy);yearValue.textContent=`今年 ${signedYen(item.yearPnlJpy)}`;values.append(totalValue,yearValue);row.append(identity,values);return row;}));
}
function render(){document.getElementById("ledgerCash").textContent=yen(loadCashBalance());const container=document.getElementById("ledgerHistory"),items=loadTransactionsFromStorage();renderRealized(items);if(!items.length){container.innerHTML='<div class="empty-holdings-state"><strong>取引履歴はまだありません</strong><p>買付・売却・入出金を登録するとここに表示されます。</p></div>';return;}container.replaceChildren(...items.map(item=>{const row=document.createElement("article");row.className=`ledger-row ledger-${item.kind.toLowerCase()}`;const head=document.createElement("div"),badge=document.createElement("b"),date=document.createElement("time");badge.textContent=item.kind;date.textContent=new Date(item.date).toLocaleString("ja-JP");head.append(badge,date);const title=document.createElement("strong");title.textContent=item.symbol?`${item.name}（${item.symbol}）`:item.kind==="DEPOSIT"?"日本円 入金":"日本円 出金";const detail=document.createElement("p");if(item.symbol){const signed=item.kind==="SELL"?"−":"＋";detail.textContent=`${signed}${number(item.quantity)} ${item.type==="crypto"?item.symbol:"株"} / ${item.type==="us"?"$":"¥"}${number(item.unitPrice)} / ${item.cashDelta>=0?"＋":"−"}${yen(Math.abs(item.cashDelta))}`;}else detail.textContent=`${item.cashDelta>=0?"＋":"−"}${yen(Math.abs(item.cashDelta))}`;row.append(head,title,detail);if(item.kind==="SELL"){const pnl=document.createElement("p");pnl.className="realized-pnl-detail";if(item.realizedPnlJpy===null){pnl.textContent="実現損益: 算出不可";pnl.classList.add("realized-unavailable");}else{pnl.textContent=`実現損益: ${signedYen(item.realizedPnlJpy)}（${Number(item.realizedPnlRate)>=0?"＋":""}${number(item.realizedPnlRate)}%）`;pnl.classList.add(item.realizedPnlJpy>0?"profit-positive":item.realizedPnlJpy<0?"profit-negative":"profit-neutral");}row.append(pnl);}return row;}));}
document.querySelectorAll("[data-kind]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-kind]").forEach(b=>b.classList.remove("active"));button.classList.add("active");kindInput.value=button.dataset.kind;clearSelection(true);renderMode();}));
typeInput.addEventListener("change",()=>{clearSelection(true);renderMode();});searchInput.addEventListener("input",queueSearch);searchInput.addEventListener("focus",()=>{if(searchInput.value.trim())queueSearch();});document.addEventListener("click",event=>{if(!event.target.closest(".ledger-asset-search"))suggestions.classList.add("hidden");});ledgerForm.addEventListener("input",estimate);
ledgerForm.addEventListener("submit",event=>{event.preventDefault();const error=document.getElementById("ledgerError");error.textContent="";try{if((kindInput.value==="BUY"||kindInput.value==="SELL")&&!chosenAsset)throw new Error("検索候補から銘柄を選択してください");commitLedgerTransaction({kind:kindInput.value,date:document.getElementById("tradeDate").value,type:typeInput.value,symbol:chosenAsset?.symbol,name:chosenAsset?.name,quantity:document.getElementById("tradeQuantity").value,unitPrice:document.getElementById("tradePrice").value,fxRate:document.getElementById("tradeFx").value,feeJpy:document.getElementById("tradeFee").value,amount:document.getElementById("cashAmount").value,coinGeckoId:chosenAsset?.coinGeckoId,yahooSymbol:chosenAsset?.yahooSymbol});ledgerForm.reset();kindInput.value=document.querySelector("[data-kind].active").dataset.kind;document.getElementById("tradeDate").value=localDateValue();typeInput.value="jp";clearSelection();renderMode();render();}catch(e){error.textContent=e.message;}});
document.getElementById("tradeDate").value=localDateValue();renderMode();render();
