const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const values = new Map();
const localStorage = {getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)};
const context={localStorage,console,structuredClone,Blob,URL,document:{createElement:()=>({}),body:{appendChild(){}}},FileReader:function(){}};
vm.createContext(context);
vm.runInContext(`${fs.readFileSync('storage.js','utf8')}\nthis.ledgerApi={applyLedgerTransaction,commitLedgerTransaction,loadTransactionsFromStorage,loadCashBalance,loadAssetsFromStorage,resetAppStorage};`,context);
const api=context.ledgerApi;
let state=api.applyLedgerTransaction([],300000,{kind:'BUY',date:'2026-08-16T12:00',type:'jp',symbol:'7203',name:'トヨタ',quantity:10,unitPrice:10000,feeJpy:0});
assert.equal(state.cashBalance,200000);assert.equal(state.assets[0].cost,10000);
state=api.applyLedgerTransaction(state.assets,state.cashBalance,{kind:'BUY',date:'2026-08-16T13:00',type:'jp',symbol:'7203',name:'トヨタ',quantity:10,unitPrice:12000,feeJpy:0});
assert.equal(state.cashBalance,80000);assert.equal(state.assets[0].amount,20);assert.equal(state.assets[0].cost,11000);
state=api.applyLedgerTransaction(state.assets,state.cashBalance,{kind:'SELL',date:'2026-08-16T14:00',type:'jp',symbol:'7203',name:'トヨタ',quantity:5,unitPrice:15000,feeJpy:1000});
assert.equal(state.cashBalance,154000);assert.equal(state.assets[0].amount,15);assert.equal(state.assets[0].cost,11000);assert.equal(state.entry.costBasisJpy,55000);
assert.throws(()=>api.applyLedgerTransaction(state.assets,state.cashBalance,{kind:'SELL',date:'2026-08-16T14:00',type:'jp',symbol:'7203',name:'トヨタ',quantity:16,unitPrice:15000}),/保有数量/);
state=api.applyLedgerTransaction(state.assets,state.cashBalance,{kind:'WITHDRAWAL',date:'2026-08-16T15:00',amount:54000});assert.equal(state.cashBalance,100000);
assert.throws(()=>api.applyLedgerTransaction(state.assets,state.cashBalance,{kind:'WITHDRAWAL',date:'2026-08-16T15:00',amount:100001}),/日本円残高/);
let us=api.applyLedgerTransaction([],500000,{kind:'BUY',date:'2026-08-16T12:00',type:'us',symbol:'NVDA',name:'NVIDIA',quantity:10,unitPrice:100,fxRate:150,feeJpy:1000});
assert.equal(us.assets[0].costJpy,15100);assert.equal(us.assets[0].acquisitionUsdJpy,151);assert.equal(us.cashBalance,349000);
api.resetAppStorage();api.commitLedgerTransaction({kind:'DEPOSIT',date:'2026-08-16T12:00',amount:200000});assert.equal(api.loadCashBalance(),200000);assert.equal(api.loadTransactionsFromStorage()[0].kind,'DEPOSIT');
api.commitLedgerTransaction({kind:'BUY',date:'2026-08-16T12:30',type:'crypto',symbol:'BTC',name:'Bitcoin',quantity:.01,unitPrice:10000000,feeJpy:0,coinGeckoId:'bitcoin'});assert.equal(api.loadCashBalance(),100000);assert.equal(api.loadAssetsFromStorage([])[0].coinGeckoId,'bitcoin');
api.resetAppStorage();assert.equal(api.loadCashBalance(),0);assert.equal(api.loadTransactionsFromStorage().length,0);
console.log('ledger tests passed');
